// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: network_comms/network_comms.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetDat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetDat) Reset() {
	*x = NetDat{}
	mi := &file_network_comms_network_comms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetDat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetDat) ProtoMessage() {}

func (x *NetDat) ProtoReflect() protoreflect.Message {
	mi := &file_network_comms_network_comms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetDat.ProtoReflect.Descriptor instead.
func (*NetDat) Descriptor() ([]byte, []int) {
	return file_network_comms_network_comms_proto_rawDescGZIP(), []int{0}
}

func (x *NetDat) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RecConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BytesReceived int64                  `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecConf) Reset() {
	*x = RecConf{}
	mi := &file_network_comms_network_comms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecConf) ProtoMessage() {}

func (x *RecConf) ProtoReflect() protoreflect.Message {
	mi := &file_network_comms_network_comms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecConf.ProtoReflect.Descriptor instead.
func (*RecConf) Descriptor() ([]byte, []int) {
	return file_network_comms_network_comms_proto_rawDescGZIP(), []int{1}
}

func (x *RecConf) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecConf) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_network_comms_network_comms_proto protoreflect.FileDescriptor

const file_network_comms_network_comms_proto_rawDesc = "" +
	"\n" +
	"!network_comms/network_comms.proto\x12\rnetwork_comms\"\"\n" +
	"\x06NetDat\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"J\n" +
	"\aRecConf\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x03R\rbytesReceived2I\n" +
	"\fServerFeeder\x129\n" +
	"\x04Feed\x12\x15.network_comms.NetDat\x1a\x16.network_comms.RecConf\"\x00(\x01B\x12Z\x10network_comms/v1b\x06proto3"

var (
	file_network_comms_network_comms_proto_rawDescOnce sync.Once
	file_network_comms_network_comms_proto_rawDescData []byte
)

func file_network_comms_network_comms_proto_rawDescGZIP() []byte {
	file_network_comms_network_comms_proto_rawDescOnce.Do(func() {
		file_network_comms_network_comms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_comms_network_comms_proto_rawDesc), len(file_network_comms_network_comms_proto_rawDesc)))
	})
	return file_network_comms_network_comms_proto_rawDescData
}

var file_network_comms_network_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_comms_network_comms_proto_goTypes = []any{
	(*NetDat)(nil),  // 0: network_comms.NetDat
	(*RecConf)(nil), // 1: network_comms.RecConf
}
var file_network_comms_network_comms_proto_depIdxs = []int32{
	0, // 0: network_comms.ServerFeeder.Feed:input_type -> network_comms.NetDat
	1, // 1: network_comms.ServerFeeder.Feed:output_type -> network_comms.RecConf
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_comms_network_comms_proto_init() }
func file_network_comms_network_comms_proto_init() {
	if File_network_comms_network_comms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_comms_network_comms_proto_rawDesc), len(file_network_comms_network_comms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_comms_network_comms_proto_goTypes,
		DependencyIndexes: file_network_comms_network_comms_proto_depIdxs,
		MessageInfos:      file_network_comms_network_comms_proto_msgTypes,
	}.Build()
	File_network_comms_network_comms_proto = out.File
	file_network_comms_network_comms_proto_goTypes = nil
	file_network_comms_network_comms_proto_depIdxs = nil
}
